/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: wallmasterr (https://sketchfab.com/wallmasterr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tenhun-falling-spaceman-fanart-9fd80b6a259f41fd99e6f56eee686dc5
Title: Tenhun Falling spaceman (FanArt)
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useMotionValue, useSpring } from "motion/react";
import { useFrame } from "@react-three/fiber";

export function ProgrammingSetup(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/louis_xiv_de_france_louvre_paris.glb"
  );
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (animations.length > 0) {
      actions[animations[0].name]?.play();
    }
  }, [actions, animations]);

  const yPosition = useMotionValue(5);
  const ySpring = useSpring(yPosition, { damping: 30 });
  useEffect(() => {
    ySpring.set(-1);
  }, [ySpring]);
  useFrame(() => {
    group.current.position.y = ySpring.get();
  });
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={props.scale || 0.3}
      position={props.position || [0, -1, 0]}
    >
      {Object.values(nodes).map((node, i) => {
        if (node.type === 'Mesh' || node.type === 'SkinnedMesh') {
          return (
            <primitive object={node} key={i} />
          );
        }
        return null;
      })}
    </group>
  );
}

// Nuevo componente para el modelo de escritorio de programador
export function ProgrammerDesktop(props) {
  const group = useRef();
  const { scene } = useGLTF("/models/programmer_desktop_3d_pc.glb");

  // Animación de entrada (opcional, similar a ProgrammingSetup)
  // Puedes agregar animaciones aquí si lo deseas

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={props.scale || 2}
      position={props.position || [0, -1, 0]}
      rotation={[0, 0, 0]}
    >
      <primitive object={scene} />
    </group>
  );
}

useGLTF.preload("/models/louis_xiv_de_france_louvre_paris.glb");
useGLTF.preload("/models/programmer_desktop_3d_pc.glb");
